### ISSUE TITLE
Better errors

### ISSUE THREAD

**Issue by ThibaudDauce** [Cosmian/findex#4]
When sending a master key of the wrong size, Rust respond with 
> Unknown Error: Failed to convert: Remaining bytes after deserialization!

We should give the user a better error when doing `let master_key = KeyingMaterial::<MASTER_KEY_LENGTH>::try_from_bytes(&master_key.to_vec())?;` (the key size expected, the key size received)

**Comment by tbrezot** [comment]
Has this been fixed in #7 ?
