### ISSUE TITLE
Compact: add batch `fetch_entry`

### ISSUE THREAD

**Issue by ackRow** [Cosmian/findex#9]
Current implementation:
- Fetch all entries UIDs
- Fetch values for these UIDs in one batch

Desired implementation:
- Add a parameter `batch_size`
- Fetch values for `batch_size` UIDs in a loop
- Code `update_lines` in Rust
- Expose simpler callbacks in client lib

**Comment by ackRow** [comment]
__Split `update_lines`__

2 implementations in Rust: cold and hot compact.

New callbacks:
- `remove_entry_table(entry_uids)`
- `remove_chain_table(chain_uids)`
- `insert_chain_table(chain_items)`
- `insert_entry_table(entry_items)`

**Comment by tbrezot** [comment]
Properly implemented in MR #57.
